### ISSUE TITLE
Некорректная информация в ReadMe

### ISSUE THREAD

**Issue by PetrIlya** [ostis-apps/ostis-example-app#15]
На текущий момент отсутсвует поддержка .gwf.
(Place for knowledge base of your app. Put your .scs and .gwf files here.)

В этом можно убедиться здесь:

https://github.com/ostis-dev/sc-machine/blob/8cb3f5a7effdf1f24d4d6cc0823c29dd4a04ef31/tools/builder/src/builder.cpp#L23

**Comment by KovalM** [comment]
.gwf не поддерживается только в ветке 0.6.0. Исправление документации для этой ветки есть в #19
